### ISSUE TITLE
报错了，buybutton位置找不到

### ISSUE THREAD

**Issue by tumnus17** [838239178/damai_tickets#1]
**Error: buybutton 位置找不到***: Message: no such element: Unable to locate element: {"method":"css selector","selector":".buy"}，移动端网页没有buybutton这个元素，请问老哥怎么解决啊

**Comment by tumnus17** [comment]
我看了下网页确实有buy这个元素的，但不知道为啥报错说没找到

**Comment by saddit** [comment]
这个可能需要自己调整一下，我这边测试没有报错的

**Comment by tumnus17** [comment]
是不是需要加个延时？我sleep1.5秒之后找到了，但又报新的错
***Error: 选择日期or场次or票档不成功***: cannot access local variable 'session' where it is not associated with a value

**Comment by saddit** [comment]
可能跟网速和配置有关 可以加一点点sleep试试看

**Comment by tumnus17** [comment]
Error: 选择日期or场次or票档不成功: cannot access local variable 'session' where it is not associated with a value
但是这个错看起来不像是sleep能解决的啊，方便说下你的python版本和浏览器版本吗，还有chromedriver的，谢啦

**Comment by tookbra** [comment]
这个就自动点击，跟抢票没啥关系，热门的票基本上抢不到的 😀

**Comment by saddit** [comment]
https://github.com/838239178/damai_tickets/blob/master/README.md
